name: blog-lb
services:
  a3blog-1:
    build: ./httpd
    container_name: a3blog-1
    ports:
      - 9051:80
  
  a3blog-2:
    build: ./httpd
    container_name: a3blog-2
    ports:
      - 9052:80

  a3blog-3:
    build: ./httpd
    container_name: a3blog-3
    ports:
      - 9053:80
  
  load-balancer:
    build: ./nginX
    container_name: lb-1
    ports:
      - 9251:80
    depends_on:
      - a3blog-1
      - a3blog-2
      - a3blog-3
    links:
      - a3blog-1
      - a3blog-2
      - a3blog-3
