name: hooniegit
version: "3.9"
services:
  blog:
    build: ../../httpd
    deploy:
      resources:
        limits:
          cpus: "0.5"    # PERCENTAGE OF CPU
          memory: 512M   # SHARED MEMORIES
    ports:
      - 80
  
  load_balancer:
    build: ../../nginX
    ports:
      - 9999:80
    depends_on:
      - blog
